### ISSUE TITLE
Error while initializing the driver under ruby 1.9.2p290

### ISSUE THREAD

**Issue by jdayo** [beverlycodes/orient_db_client#1]
When doing:

OrientDbClient.connect(host, :port => port)

Getting Error:

OrientDbClient::UnsupportedProtocolError: The host reports protocol version 2304, which is not currently supported by this driver

most likely due to unpack being broken in 1.9.2

**Comment by beverlycodes** [comment]
Looked into this issue.  I wrote this under Ruby 1.9.3, which has an unpack implementation that supports explicitly reading both big- and little-endian integer data.  I didn't realize until now that Ruby 1.9.2 only supports unpacking big-endian integers when it's running on a big-endian architecture.  Anyone running on an Intel platform is left with no ability to correctly unpack big-endian data.  That's a pretty embarrassing oversight on the part of the Ruby developers.  Obviously they realized that, but the fix doesn't appear to have been back-ported to 1.9.2 (at least not as of p318)

If you can upgrade to Ruby 1.9.3, it will resolve the issue.  I'll need to look into writing (or adding a dependency for) an unpack alternative in order to support 1.9.2.

**Comment by beverlycodes** [comment]
I'm going to retrofit all of the network IO with the BinData gem.  Initial testing has been successful under 1.9.2 and 1.9.3.  Look for an update sometime in the next 48 hours.

**Comment by jdayo** [comment]
Awesome! thanks ryan
On May 9, 2012 5:09 PM, "Ryan Fields" <
reply@reply.github.com>
wrote:

**Comment by beverlycodes** [comment]
I've finished the overhaul of all of the pack/unpack usage and released version 0.0.4 of this gem.  This adds the BinData gem as a runtime dependency (which should be taken care of by Bundler if you're using it.)

My tests aren't as complete as I'd like them to be, but they all passed so hopefully everything that was working in version 0.0.3 is still working in 0.0.4.  I'm not currently using this gem in any active projects so I'm not able to test in any "production-grade" scenarios.  I'm happy to continue providing support and bug fixes though.
